// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef GoodBoiGUI_h
#define GoodBoiGUI_h
#include <FL/Fl.H>
void connect_Button_CB(Fl_Widget*, void*);
void start_Button_CB(Fl_Widget*, void*);
void stop_Button_CB(Fl_Widget*, void*);
void send_Button_CB(Fl_Widget*, void*);
void controlButtons_CB(Fl_Widget*,  int buttonNum);
void OpenLoopOffset_CB(Fl_Widget*,int num);
void* updateSerialMsgWindowThread(void*);
void* updateDataDisplayThread(void*);
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
extern Fl_Group *control_Group;
#include <FL/Fl_Button.H>
extern Fl_Button *downArrow_Button;
extern Fl_Button *leftArrow_Button;
extern Fl_Button *rightArrow_Button;
extern Fl_Button *upArrow_Button;
extern Fl_Button *stand_Button;
extern Fl_Button *sit_Button;
extern Fl_Button *layDown_Button;
extern Fl_Button *walk_Button;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *stepDist_Valuator;
extern Fl_Value_Input *walkSpeed_Valuator;
extern Fl_Value_Input *walkHeight_Valuator;
extern Fl_Value_Input *walkDir_Valuator;
extern Fl_Value_Input *openLoopOffset1X_Valuator;
extern Fl_Value_Input *openLoopOffset1Y_Valuator;
extern Fl_Value_Input *openLoopOffset2X_Valuator;
extern Fl_Value_Input *openLoopOffset2Y_Valuator;
extern Fl_Value_Input *openLoopOffset3X_Valuator;
extern Fl_Value_Input *openLoopOffset3Y_Valuator;
extern Fl_Value_Input *openLoopOffset4X_Valuator;
extern Fl_Value_Input *openLoopOffset4Y_Valuator;
extern Fl_Group *logData_Group;
#include <FL/Fl_File_Input.H>
#include <FL/Fl_Input.H>
extern Fl_Group *comms_Group;
extern Fl_Input *commsInput;
extern Fl_Button *send_Button;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *commsOutput_Output;
extern Fl_Group *displayData_Group;
#include <FL/Fl_Value_Output.H>
extern Fl_Value_Output *xAcc_Value;
extern Fl_Value_Output *yAcc_Value;
extern Fl_Value_Output *zAcc_Value;
extern Fl_Value_Output *xGyro_Value;
extern Fl_Value_Output *yGyro_Value;
extern Fl_Value_Output *zGyro_Value;
#include <FL/Fl_Output.H>
extern Fl_Output *errorMsg_TextDisplay;
extern Fl_Button *connect_button;
extern Fl_Text_Display *status_TextDisplay;
extern Fl_Button *start_Button;
extern Fl_Button *stop_Button;
extern Fl_Input *baudRate_Input;
#endif
